log/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required
from . import views

urlpatterns = [
    path('job/<int:pk>', login_required(views.LogDetail.as_view()), name='job_detail'),
    path('create', login_required(views.LogCreate.as_view()), name='job_create'),
    path('update/<int:pk>', login_required(views.LogUpdate.as_view()), name='job_update'),
    path('delete/<int:pk>', login_required(views.LogDelete.as_view()), name='job_delete'),
    path('', login_required(views.search), name='search'),
    path('chart', login_required(views.LogChart), name='job_chart'),
    ]

timesheet/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.utils.translation import ugettext_lazy as altname

urlpatterns = [
    url(r'', include('log.urls')),
    url(r'^log/', include('log.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]
'''
if settings.DEBUG is False:   #if DEBUG is True it will be served automatically
    urlpatterns += patterns('',
            url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    )
'''

admin.site.site_header = ' '
admin.site.site_title = "Timesheet Admin"
admin.site.index_title = "🕓 / Timesheet Administration"
#admin

urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.utils.translation import ugettext_lazy as altname

urlpatterns = [
    url(r'', include('log.urls')),
    url(r'^log/', include('log.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

admin.site.site_header = altname("Timesheet Administration")
admin.site.site_title = altname("Timesheet Admin")

log/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum

class Project(models.Model):
    projectname = models.CharField('Project Name', max_length=255)
    projectleader = models.ForeignKey(User, related_name='Leader', null=True, blank=True, default=1, on_delete=models.SET_DEFAULT)
    costperhour = models.DecimalField('Cost Per Hour', max_digits=10, decimal_places=2, default=0)
    def totalcost(self):
        costs = LogEntry.objects.aggregate(totalcost=(Sum('cost')))
        costformat = format(round(costs['totalcost'],2))
        return costformat
    def __str__(self):
        return self.projectname

class LogEntry(models.Model):
    loggedjob = models.CharField('Job Name',max_length=255)
    starttime = models.DateTimeField('Start Time')
    finishtime = models.DateTimeField('Finish Time')
    jobtime = models.DurationField(editable=False)
    project = models.ForeignKey(Project, default="None", on_delete=models.CASCADE)
    description = models.CharField('Description',max_length=255, blank=True)
    cost = models.DecimalField('Job Cost', decimal_places=2, max_digits=20, editable=False, default=0)
    worker = models.ForeignKey(User, related_name="worker", null=True, blank=True, default=1, on_delete=models.SET_DEFAULT)
    def save(self, *args, **kwargs):
        self.jobtime = None
        self.cost = None
        if not self.jobtime:
            self.jobtime = self.finishtime-self.starttime
        if not self.cost:
            self.jtime = float(self.jobtime.total_seconds())
            self.cost = float(self.project.costperhour)
            self.hours = ((self.jtime/60)/60)
            self.hoursround = format(round(self.hours,2))
            self.cost = format(round(self.cost*(self.jtime/60)/60,2))
        super().save(*args, **kwargs)
    def __str__(self):
        return self.loggedjob

log/views.py
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from bootstrap_datepicker_plus import DateTimePickerInput
from .models import LogEntry
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .filters import LogFilter
from django.shortcuts import render


def LogChart(request):
    if request.user.is_staff == False:
        currentuser = request.user
        job_list = LogEntry.objects.all().filter(worker=currentuser)
    else:
        job_list = LogEntry.objects.all()
    #job_list = LogEntry.objects.all()
    job_filter = LogFilter(request.GET, queryset=job_list)
    return render(request, 'log/job_chart.html', {'filter': job_filter})

def search(request):
    if request.user.is_staff == False:
        currentuser = request.user
        job_list = LogEntry.objects.all().filter(worker=currentuser)
    else:
        job_list = LogEntry.objects.all()
    #job_list = LogEntry.objects.all()
    job_filter = LogFilter(request.GET, queryset=job_list)
    return render(request, 'log/job_filter.html', {'filter': job_filter})

class LogDetail(DetailView):
    model = LogEntry
    template_name = 'log/job_detail.html'
    def get_queryset(self):
        if self.request.user.is_staff == False:
            return self.model.objects.filter(worker=self.request.user)
        else:
            return self.model.objects.all()

class LogCreate(CreateView):
    model = LogEntry
    fields = ['loggedjob', 'starttime', 'finishtime', 'description', 'project']
    def get_form(self):
        form = super().get_form()
        form.fields['loggedjob']
        form.fields['description']
        form.fields['starttime'].widget = DateTimePickerInput(format='%Y-%m-%d %H:%M:%S')
        form.fields['finishtime'].widget = DateTimePickerInput(format='%Y-%m-%d %H:%M:%S')
        return form
    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.worker = self.request.user
        return super(CreateView, self).form_valid(form)
    success_url = reverse_lazy('search')
    template_name = 'log/job_form.html'

class LogUpdate(UpdateView):
    model = LogEntry
    fields = ['loggedjob', 'starttime', 'finishtime', 'description']
    success_url = reverse_lazy('search')
    template_name = 'log/job_form.html'
    def get_queryset(self):
        if self.request.user.is_staff == False:
            return self.model.objects.filter(worker=self.request.user)
        else:
            return self.model.objects.all()

class LogDelete(DeleteView):
    model = LogEntry
    success_url = reverse_lazy('search')
    template_name = 'log/job_confirm_delete.html'
    def get_queryset(self):
        if self.request.user.is_staff == False:
            return self.model.objects.filter(worker=self.request.user)
        else:
            return self.model.objects.all()

log/templates/change_list_graph.html
{% extends "admin/change_list.html" %}
{% load staticfiles %}
{% block extrahead %}
{% load logtags %}
{% load static %}

<script type="text/javascript" src="{% static "Chart.min.js" %}"></script>
    <script>
        var randomColorGenerator = function () {
            return '#' + (Math.random().toString(16) + '0000000').slice(2, 8);
        };
        var options = {
            responsive: true,
            maintainAspectRatio: true,
            legend: {
                display: false,
                position: 'left'
            },
 
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                        }
                    }]
                },
            animation: {
                animateScale: true,
                animateRotate: true
            }
        };
        window.onload = function () {
            var ctx = document.getElementById("work-chart");
            {% regroup cl.queryset|dictsort:"loggedjob" by worker as worklist %}
            {% regroup cl.queryset|dictsort:"loggedjob" by get_worker_display as perwork %}
            var lineChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: [{% for i in worklist %}'{{ i.grouper }}',{% endfor %}],
                    datasets: [{
                        data: [{% for i in worklist %}'{{ i.list|length }}',{% endfor %}],
                        backgroundColor: [{% for i in cl.queryset %}randomColorGenerator(),{% endfor %}]
                    }]
                },
            options: {
                responsive: true,
                maintainAspectRatio: true,
                legend: {
                    display: false,
                    position: 'left'
                        },
                title: {
                    display: true,
                    text: "Jobs Per User"
                    },
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                                }
                            }]
                        },
                animation: {
                    animateScale: true,
                    animateRotate: true
                            }
                        }
            });
            
           var ctx = document.getElementById("proj-chart");
            {% regroup cl.queryset|dictsort:"cost"|dictsort:"project.projectname" by project.projectname as projtimee %}
            var lineChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: [{% for i in projtimee %}'{{ i.grouper }}',{% endfor %}],
                    datasets: [{
                        data: [{% for i in projtimee %}'{{ i.list|running_total }}',{% endfor %}],
                        backgroundColor: [{% for i in projtimee %}randomColorGenerator(),{% endfor %}]
                    }]
                },
            options: {
                responsive: true,
                maintainAspectRatio: true,
                legend: {
                    display: false,
                    position: 'left'
                        },
                title: {
                    display: true,
                    text: "Cost Per Project"
                    },
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                                }
                            }]
                        },
                animation: {
                    animateScale: true,
                    animateRotate: true
                            }
                        }
            });
            
            var ctx = document.getElementById("job-chart");
            {% regroup cl.queryset|dictsort:"project.projectname" by project.projectname as joblist %}
            var lineChart = new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: [{% for i in joblist %}'{{ i.grouper }}',{% endfor %}],
                    datasets: [{
                        data: [{% for i in joblist %}'{{ i.list|length }}',{% endfor %}],
                        backgroundColor: [{% for i in cl.queryset %}randomColorGenerator(),{% endfor %}]
                    }]
                },

            options: {
                responsive: true,
                maintainAspectRatio: true,
                legend: {
                    display: true,
                    position: 'left'
                        },
                title: {
                    display: true,
                    text: "Jobs Per Project"
                    },

                animation: {
                    animateScale: true,
                    animateRotate: true
                            }
                        }
        });

}
    </script>
{% endblock %}
{% block content %}

<table class="table table-striped">
    <tr>
        <td>
            <canvas id="job-chart"></canvas>
        </td>
        <td>
            <canvas id="work-chart"></canvas>
        </td>
        <td>
            <canvas id="proj-chart"></canvas>
        </td>
    </tr>
</table>

    {{ block.super }}
{% endblock %}

log/templates/change_list_project_graph.html
{% extends "admin/change_list.html" %}
{% load staticfiles %}
{% block extrahead %}
{% load static %}

<script type="text/javascript" src="{% static "Chart.min.js" %}"></script>
    <script>
        var randomColorGenerator = function () {
            return '#' + (Math.random().toString(16) + '0000000').slice(2, 8);
        };
        var options = {
            responsive: true,
            maintainAspectRatio: true,
            legend: {
                position: 'left'
            },
            title: {
                display: true,
                text: "Projects"
            },
            animation: {
                animateScale: true,
                animateRotate: true
            }
        };
        window.onload = function () {
            var ctx = document.getElementById("project-chart");
            {% regroup cl.queryset|dictsort:"projectleader.username" by projectleader.username as joblist %}
            var lineChart = new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: [{% for i in joblist %}'{{ i.grouper }}',{% endfor %}],
                    datasets: [{
                        data: [{% for i in joblist %}'{{ i.list|length }}',{% endfor %}],
                        backgroundColor: [{% for i in cl.queryset %}randomColorGenerator(),{% endfor %}]
                    }]
                },
                options: options
            });
        }
    </script>
{% endblock %}
{% block content %}
    <table class="table table-striped">
    <tr>
        <td>
            <canvas id="project-chart"></canvas>
        </td>
    </tr>
    </table>
    {{ block.super }}
{% endblock %}

log/templates/log/base.html
{% load static %}
{% load logtags %}
<link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}"/>
{% load bootstrap4 %}
{% if 'use_i18n'|bootstrap_setting %}
    {% load i18n %}
    {% get_current_language as LANGUAGE_CODE %}
{% endif %}

<html lang="{{ LANGUAGE_CODE|default:'en_us' }}">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Page title -->
    <title>{% block bootstrap4_title %}Time Sheet{% endblock %}</title>
    <!-- Bootstrap CSS -->
    {% bootstrap_css %}
    <!-- Bootstrap JavaScript if it is in head -->
    {% if 'javascript_in_head'|bootstrap_setting %}
        {% bootstrap_javascript %}
    {% endif %}
    {% block bootstrap4_extra_head %}{% endblock %}
</head>

<body>
{% block bootstrap4_before_content %}{% endblock %}
{% block bootstrap4_content %} 
    
    {% block navbar %}
    {% endblock %}

{% endblock %}
{% block bootstrap4_after_content %}{% endblock %}

<!-- Bootstrap JavaScript if it is in body -->
{% if not 'javascript_in_head'|bootstrap_setting %}
    {% bootstrap_javascript %}
{% endif %}

{% block bootstrap4_extra_script %}{% endblock %}

</body>

</html>

log/templates/log/job_chart.html
{% extends 'log/navbar.html' %}
{% load logtags %}
{% load crispy_forms_tags %}
{% block content %}
{% load static %}
<script type="text/javascript" src="{% static "Chart.min.js" %}"></script>
    <script>
        var randomColorGenerator = function () {
            return '#' + (Math.random().toString(16) + '0000000').slice(2, 8);
        };
        var options = {
            responsive: true,
            maintainAspectRatio: true,
            legend: {
                display: false,
                position: 'left'
            },

            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                        }
                    }]
                },
            animation: {
                animateScale: true,
                animateRotate: true
            }
        };
        window.onload = function () {
            var ctx = document.getElementById("jobs-per-user");
            {% regroup filter.qs|dictsort:"worker.username" by worker.username as worklist %}
            var lineChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: [{% for i in worklist %}'{{ i.grouper }}',{% endfor %}],
                    datasets: [{
                        data: [{% for i in worklist %}'{{ i.list|length }}',{% endfor %}],
                        backgroundColor: [{% for i in worklist %}randomColorGenerator(),{% endfor %}]
                    }]
                },
            options: {
                responsive: true,
                maintainAspectRatio: true,
                legend: {
                    display: false,
                    position: 'left'
                        },
                title: {
                    display: true,
                    text: "Jobs Per User"
                    },
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                                }
                            }]
                        },
                animation: {
                    animateScale: true,
                    animateRotate: true
                            }
                        }
            });

            var ctx = document.getElementById("cost-per-project");
            {% regroup filter.qs|dictsort:"cost"|dictsort:"project.projectname" by project.projectname as projtimee %}
            var lineChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: [{% for i in projtimee %}'{{ i.grouper }}',{% endfor %}],
                    datasets: [{
                        data: [{% for i in projtimee %}'{{ i.list|running_total }}',{% endfor %}],
                        backgroundColor: [{% for i in projtimee %}randomColorGenerator(),{% endfor %}]
                    }]
                },
            options: {
                responsive: true,
                maintainAspectRatio: true,
                legend: {
                    display: false,
                    position: 'left'
                        },
                title: {
                    display: true,
                    text: "Cost Per Project"
                    },
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                                }
                            }]
                        },
                animation: {
                    animateScale: true,
                    animateRotate: true
                            }
                        }
            });

            var ctx = document.getElementById("jobs-per-project");
            {% regroup filter.qs|dictsort:"project.projectname" by project.projectname as joblist %}
            var lineChart = new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: [{% for i in joblist %}'{{ i.grouper }}',{% endfor %}],
                    datasets: [{
                        data: [{% for i in joblist %}'{{ i.list|length }}',{% endfor %}],
                        backgroundColor: [{% for i in joblist %}randomColorGenerator(),{% endfor %}]
                    }]
                },

            options: {
                responsive: true,
                maintainAspectRatio: true,
                legend: {
                    display: true,
                    position: 'left'
                        },
                title: {
                    display: true,
                    text: "Jobs Per Project"
                    },

                animation: {
                    animateScale: true,
                    animateRotate: true
                            }
                        }
        },);

            var ctx = document.getElementById("cost-per-job");
            var lineChart = new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: [{% for i in filter.qs %}'{{ i.loggedjob }}',{% endfor %}],
                    datasets: [{
                        data: [{% for i in filter.qs %}'{{ i.cost|slugify }}',{% endfor %}],
                        backgroundColor: [{% for i in filter.qs %}randomColorGenerator(),{% endfor %}]
                    }]
                },
                options: {
                    responsive: true,
                    maintainAspectRatio: true,
                    legend: {
                        display: true,
                        position: 'left'
                    },
                    title: {
                        display: true,
                        text: "Cost Per Job"
                    },
                    animation: {
                        animateScale: true,
                        animateRotate: true
                    }
                }
                });
    }
</script>

<title>
{% block title %}Time Sheet{% endblock %}
</title>

<form class="form-inline" method="get">
    <div class="form-group row">{{ filter.form|crispy }}</div>
        <div class="col">
        <button class="btn btn-primary" type="submit">Search</button>
        </div>
</form>
<a href="{% url 'search' %}">Home</a>
<table class="table table-striped">
    <thead>
    <tr>
        <th>Total Cost: £{{ filter.totalcost }}</th>
        <th>Total Time: {{ filter.totaltimespent }}</th>
    </tr>
    </thead>
    <tr>
        <td>
            <canvas id="jobs-per-project"></canvas>
        </td>
        <td>
            <canvas id="cost-per-project"></canvas>
        </td>
    </tr>
    <tr>
        <td>
            <canvas id="jobs-per-user"></canvas>
        </td>
        <td>
            <canvas id="cost-per-job"></canvas>
        </td>
    </tr>
</table>

{% endblock %}

log/templates/log/job_confirm_delete.html
{% extends 'log/navbar.html' %}
{% block content %}
<div class="form-confirm">
<form class="form-group"  method="post">
    <h2>Delete Job ?</h2>
    {% csrf_token %}
    Are you sure you want to delete this job?
    <div class="col">
    <input class="btn btn-primary" type="submit" value="Submit" />
    </div>
</form>
</div>

{% endblock %}

log/templates/log/job_detail.html
{% extends 'log/navbar.html' %}
{% block content %}
<table class="table table-striped">
    <td>
        Job Details
    </td>
    <td>
        &nbsp;
    </td>
    <td>
        Job: {{object.loggedjob}}
    </td>
    <td>
        Start Time: {{object.starttime}}
    </td>
    <td>
        Finish Time: {{object.finishtime}}
    </td>
    <td>
        Project: {{object.project}}
    </td>
    <td>
        Worker: {{object.worker}}
    </td>
    <td>
        Description: {{object.description}}
    </td>
</table>
{% endblock %}

log/templates/log/job_filter.html
{% extends 'log/navbar.html' %}
{% load logtags %}
{% block content %}
{% load crispy_forms_tags %}

<title>
{% block title %}Time Sheet{% endblock %}
</title>

<form class="form-inline" method="get">
    <div class="form-group row">{{ filter.form|crispy }}</div>
        <div class="col">
        <button class="btn btn-primary" type="submit">Search</button>
        </div>
</form>

<div class="panel panel-default">
    <div class="row">
        <div class="col">Time Now: {% now "SHORT_DATETIME_FORMAT" %} </div>
        <div class="col">Welcome: {{ user.username }} </div>
        <div class="col">Time Spent Total: {{ filter.totaltimespent }}</div>
        <div class="col">Total Cost: £{{ filter.totalcost }}</div>
        <div class="col"><a href="{% url "job_create" %}">Add Job</a></div>
        <div class="col"><a href="{% url "job_chart" %}">Charts</a></div>
    </div>
</div>
    
<table class="table table-striped">
    <thead>
    <tr>
        <th>Job Name</th>
        <th>Start Time</th>
        <th>Finish Time</th>
        <th>Description</th>
        <th>Worker</th>
        <th>Project</th>
        <th>Time Spent</th>
        <th>Job Cost</th>
        <th>Cost Per Hour</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
    </tr>
    </thead>

{% for job in filter.qs %}
    <tr>
        <td>{{ job.loggedjob }}</td>
        <td>{{ job.starttime|date:"H:i Y-m-d" }}</td>
        <td>{{ job.finishtime|date:"H:i Y-m-d" }}</td>
        <td>{{ job.description }}</td>
        <td>{{ job.worker }}</td>
        <td>{{ job.project }}</td>
        <td>{{ job.jobtime }}</td>
        <td>£{{ job.cost }}</td>
        <td>£{{ job.project.costperhour }}</td>
        <td><a  href="{% url "job_detail"  job.id  %}">details</a></td>
        <td><a  href="{% url "job_update"  job.id  %}">edit</a></td>
        <td><a  href="{% url "job_delete"  job.id  %}">delete</a></td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

log/templates/log/job_form.html
{% extends 'log/navbar.html' %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% block content %}
{{ form.media }}
            <form class="form-group" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                <button type="submit" value="Submit" class="btn btn-primary">
                Save
                </button>
                {% endbuttons %}
            </form>
{% endblock %}

log/templates/log/navbar.html
{% extends 'log/base.html' %}
{% load logtags %}
{% block navbar %}

<div class="container">
    {% block content %}{% endblock %}
</div>

{% endblock %}

templates/401.html
{% extends 'log/navbar.html' %}
{% load logtags %}
{% load crispy_forms_tags %}
{% block content %}
{% load static %}

<h1>🕓</h1>
<h2>Error</h2>

{% endblock %}